create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists categories_is_active_idx on public.categories (is_active);

insert into public.categories (slug, title, is_active)
values
  ('empanadas', 'Empanadas Artesanales', true),
  ('salchipapas', 'Salchipapas Q''Bacano', true),
  ('postres', 'Postres Caseros', true),
  ('extras', 'Extras', true),
  ('bebidas', 'Bebidas', true)
on conflict (slug) do nothing;
