create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  price numeric(10,2) not null,
  category text not null,
  image_url text,
  image_public_id text,
  available boolean not null default true,
  is_combo boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_category_idx on public.products (category);
create index if not exists products_available_idx on public.products (available);

-- Insertar productos de ejemplo
insert into public.products (name, description, price, category, image_url, available, is_combo)
values
  -- Empanadas
  ('Empanada de Carne', 'Carne molida jugosa con cebolla, pimiento y un toque de comino.', 2.50, 'empanadas', 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=600&q=80', true, false),
  ('Empanada de Queso', 'Queso derretido y jamón de primera, horneadas a la perfección.', 2.50, 'empanadas', 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=600&q=80', true, false),
  ('Empanada de Pollo', 'Pollo desmenuzado con verduras y especias.', 2.25, 'empanadas', 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=600&q=80', true, false),
  ('Empanada Mixta', 'Carne y queso, la combinación perfecta.', 3.00, 'empanadas', 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=600&q=80', true, false),
  
  -- Salchipapas
  ('Salchipapa Clásica', 'Salchicha con papas doradas, queso y salsas.', 4.50, 'salchipapas', 'https://images.unsplash.com/photo-1568901346403-7f25e5d3ac4e?auto=format&fit=crop&w=600&q=80', true, false),
  ('Salchipapa Especial', 'Doble salchicha, bacon, cheddar y papas.', 6.00, 'salchipapas', 'https://images.unsplash.com/photo-1568901346403-7f25e5d3ac4e?auto=format&fit=crop&w=600&q=80', true, false),
  ('Salchipapa Mixta', 'Salchicha, chorizo, pollo con todas las salsas.', 7.50, 'salchipapas', 'https://images.unsplash.com/photo-1568901346403-7f25e5d3ac4e?auto=format&fit=crop&w=600&q=80', true, false),
  
  -- Postres
  ('Flan Casero', 'Flan tradicional con caramelo hecho en casa.', 3.50, 'postres', 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?auto=format&fit=crop&w=600&q=80', true, false),
  ('Tres Leches', 'Pastel de tres leches, esponjoso y delicioso.', 4.00, 'postres', 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?auto=format&fit=crop&w=600&q=80', true, false),
  ('Brownie con Helado', 'Brownie de chocolate con bola de helado de vainilla.', 4.50, 'postres', 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?auto=format&fit=crop&w=600&q=80', true, false),
  
  -- Extras
  ('Queso Extra', 'Porción adicional de queso derretido.', 1.50, 'extras', 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?auto=format&fit=crop&w=600&q=80', true, false),
  ('Bacon Extra', 'Porción adicional de bacon crujiente.', 2.00, 'extras', 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?auto=format&fit=crop&w=600&q=80', true, false),
  ('Salsas Extra', 'Mix de salsas especiales (mayo, ketchup, mostaza).', 0.75, 'extras', 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?auto=format&fit=crop&w=600&q=80', true, false),
  
  -- Bebidas
  ('Refresco de Cola', 'Refresco de cola 355ml.', 2.00, 'bebidas', 'https://images.unsplash.com/photo-1546776392-f007e691ce13?auto=format&fit=crop&w=600&q=80', true, false),
  ('Agua de Sabor', 'Agua fresca del día (horchata, jamaica, tamarindo).', 2.50, 'bebidas', 'https://images.unsplash.com/photo-1546776392-f007e691ce13?auto=format&fit=crop&w=600&q=80', true, false),
  ('Jugo Natural', 'Jugo de naranja o limón recién exprimido.', 3.00, 'bebidas', 'https://images.unsplash.com/photo-1546776392-f007e691ce13?auto=format&fit=crop&w=600&q=80', true, false)
on conflict do nothing;
